### ISSUE TITLE
Could not resolve cross-reference to Verse.GeneDef named AG_InnatePsylink (wanter=blackListedGenes)

### ISSUE THREAD

**Issue by User-Name54321** [juanosarg/AlphaGenes#3]
When I install sarg.alphagenes version 1.703(this does not happen with 1.702), upon starting RimWorld(RimWorld 1.4.3704 rev886) I get this error "Could not resolve cross-reference to Verse.GeneDef named AG_InnatePsylink (wanter=blackListedGenes)" The currently installed mods are Vanilla Expanded Framework(dated 09/06/23) and Harmony 1.5. I apologize as I do not use HugsLib and cannot find the logs, and I will instead attach part of the Unity player.log.

[test.txt](https://github.com/juanosarg/AlphaGenes/files/11780096/test.txt)

**Comment by juanosarg** [comment]
This one was fixed
